name: miserere
description: Miserere e Settimana Santa a Piano di Sorrento

version: 2.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.3.1
  http: ^0.13.4
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  supabase_flutter: ^0.2.12
  webview_flutter: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon/miserere.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Morris
      fonts:
        - asset: assets/fonts/morris_roman/MorrisRomanBlack.ttf